version: '2.1'  
services:  
  caddy:
    build: .
    image: c230a52ed136
    container_name: plexmediaserver
    volumes:
      - C:\temp\docker\plex_meta:c:\PlexData
      - C:\temp\docker\plex_data:c:\media
    network_mode: nat
    restart: unless-stopped
    ports:
      - 32400:32400
      - 32400:32400/udp
      - 32469:32469
      - 32469:32469/udp
      - 5353:5353/udp
      - 1900:1900/udp
      - 3005:3005
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PLEX_MEDIA_SERVER_INFO_DEVICE=docker